# patch_s138_mushaf_reciter_listen.py
#
# lib/screens/mushaf_screen.dart -- tapping an ayah opens the existing
# "ayah actions" sheet (تفسير / مشاركة / نسخ / استخدام في الاستوديو), which
# had no audio option: hearing a reciter, or grabbing their recitation for
# offline reading, meant leaving المصحف entirely for the studio's own
# reciter panel (home_screen.dart, S104).
#
# This adds a new "استماع" action to that sheet. It opens a self-contained
# reciter list (kReciters, already used by the studio panel) for the
# ayah's surah:
#   - tap a name to stream it: ReciterAudioService downloads (or reuses
#     its permanent on-disk cache) then plays with video_player, same
#     audio-only pattern the studio's reciter preview already uses.
#   - a separate download button caches the surah for offline reading
#     without starting playback.
#   - a search field narrows the list, which the studio panel's plain
#     ListView never had.
#
# Concurrency: the studio panel (S104) tracked download state with a
# single `int? _downloadingReciter`, so starting a second reciter's
# download before the first finished wasn't possible -- the field could
# only ever point at one index. This sheet keeps a `Map<int, double?>`
# instead, one entry per in-flight reciter, so several downloads can run
# side by side; nothing here serializes them.
#
# No changes to ReciterAudioService itself (lib/services/reciter_audio_service.dart,
# added in S104) -- this reuses it as-is; its on-disk cache is what makes a
# downloaded reciter "for offline reading" rather than a one-time stream.
#
# Run from the project root.

from pathlib import Path

ROOT = Path(__file__).resolve().parent
LEDGER = []
MARKER = "PATCH_S138_MUSHAF_RECITER_LISTEN"
MARKER_IMPORTS = "PATCH_S138_IMPORTS"
MARKER_ACTION = "PATCH_S138_LISTEN_ACTION"
MARKER_OPEN = "PATCH_S138_OPEN_SHEET"
MARKER_SHEET = "PATCH_S138_RECITER_SHEET"


def _log(label, status):
    LEDGER.append((label, status))


def apply_literal(rel_path, old, new, label, skip_if=None):
    p = ROOT / rel_path
    if not p.exists():
        raise SystemExit(f"ERROR ({label}): {rel_path} not found under {ROOT}")
    text = p.read_text(encoding="utf-8")
    if skip_if and skip_if in text:
        _log(label, "SKIPPED-ALREADY")
        return
    n = text.count(old)
    if n != 1:
        raise SystemExit(f"ERROR ({label}): expected 1 match, found {n} in {rel_path} "
                          f"-- refusing to guess, no changes made.")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")
    _log(label, "APPLIED")


MUSHAF = "lib/screens/mushaf_screen.dart"


def main():
    # -----------------------------------------------------------------
    # 1) imports -- dart:io + video_player for playback, studio_presets
    #    for kReciters, reciter_audio_service for the download/cache.
    # -----------------------------------------------------------------
    apply_literal(
        MUSHAF,
        "import 'dart:math';\n"
        "\n"
        "import 'package:flutter/gestures.dart';\n"
        "import 'package:flutter/material.dart';\n"
        "import 'package:flutter/services.dart';\n"
        "import 'package:google_fonts/google_fonts.dart';\n"
        "import 'package:share_plus/share_plus.dart';\n"
        "\n"
        "import '../data/mushaf_meta.dart';\n"
        "import '../i18n/app_strings.dart';\n"
        "import '../services/app_settings.dart';\n"
        "import '../services/ayah_matcher.dart';\n"
        "import '../services/quran_search.dart';\n"
        "import '../services/tafsir_service.dart';\n"
        "import '../theme/ayat_fonts.dart';\n"
        "import '../theme/mushaf_theme.dart';\n"
        "import '../widgets/motion.dart';\n",
        f"import 'dart:io'; // {MARKER_IMPORTS}: File for the downloaded/cached mp3\n"
        "import 'dart:math';\n"
        "\n"
        "import 'package:flutter/gestures.dart';\n"
        "import 'package:flutter/material.dart';\n"
        "import 'package:flutter/services.dart';\n"
        "import 'package:google_fonts/google_fonts.dart';\n"
        "import 'package:share_plus/share_plus.dart';\n"
        f"import 'package:video_player/video_player.dart'; // {MARKER_IMPORTS}\n"
        "\n"
        "import '../data/mushaf_meta.dart';\n"
        f"import '../data/studio_presets.dart'; // {MARKER_IMPORTS}: kReciters\n"
        "import '../i18n/app_strings.dart';\n"
        "import '../services/app_settings.dart';\n"
        "import '../services/ayah_matcher.dart';\n"
        "import '../services/quran_search.dart';\n"
        f"import '../services/reciter_audio_service.dart'; // {MARKER_IMPORTS}\n"
        "import '../services/tafsir_service.dart';\n"
        "import '../theme/ayat_fonts.dart';\n"
        "import '../theme/mushaf_theme.dart';\n"
        "import '../widgets/motion.dart';\n",
        "mushaf_screen.dart: imports for reciter listen/download",
        skip_if=MARKER_IMPORTS,
    )

    # -----------------------------------------------------------------
    # 2) a new _SheetAction in the per-ayah actions sheet, between تفسير
    #    and مشاركة, opening the reciter sheet for that ayah's surah.
    # -----------------------------------------------------------------
    apply_literal(
        MUSHAF,
        "                _SheetAction(\n"
        "                  palette: _p,\n"
        "                  icon: Icons.menu_book_outlined,\n"
        "                  label: _s.t('mushaf.tafsir'),\n"
        "                  onTap: () {\n"
        "                    Navigator.pop(sheetCtx);\n"
        "                    _tabs.animateTo(2);\n"
        "                  },\n"
        "                ),\n"
        "                _SheetAction(\n"
        "                  palette: _p,\n"
        "                  icon: Icons.ios_share_outlined,\n"
        "                  label: _s.t('common.share'),\n",
        "                _SheetAction(\n"
        "                  palette: _p,\n"
        "                  icon: Icons.menu_book_outlined,\n"
        "                  label: _s.t('mushaf.tafsir'),\n"
        "                  onTap: () {\n"
        "                    Navigator.pop(sheetCtx);\n"
        "                    _tabs.animateTo(2);\n"
        "                  },\n"
        "                ),\n"
        f"                // {MARKER_ACTION}: hear a reciter or cache one for\n"
        "                // offline reading, without leaving المصحف.\n"
        "                _SheetAction(\n"
        "                  palette: _p,\n"
        "                  icon: Icons.graphic_eq,\n"
        "                  label: 'استماع',\n"
        "                  onTap: () {\n"
        "                    Navigator.pop(sheetCtx);\n"
        "                    _openReciterSheet(ayah);\n"
        "                  },\n"
        "                ),\n"
        "                _SheetAction(\n"
        "                  palette: _p,\n"
        "                  icon: Icons.ios_share_outlined,\n"
        "                  label: _s.t('common.share'),\n",
        "mushaf_screen.dart: add 'استماع' action to the ayah sheet",
        skip_if=MARKER_ACTION,
    )

    # -----------------------------------------------------------------
    # 3) _openReciterSheet on _MushafScreenState -- just launches the new
    #    self-contained sheet widget (added in step 4), which owns its
    #    own download/playback state so nothing needs adding to
    #    _MushafScreenState's fields or dispose().
    # -----------------------------------------------------------------
    apply_literal(
        MUSHAF,
        "                ),\n"
        "                if (widget.onUseAyah != null)\n"
        "                  _SheetAction(\n"
        "                    palette: _p,\n"
        "                    icon: Icons.movie_creation_outlined,\n"
        "                    label: _s.t('mushaf.useInStudio'),\n"
        "                    highlighted: true,\n"
        "                    onTap: () {\n"
        "                      Navigator.pop(sheetCtx);\n"
        "                      widget.onUseAyah!(ayah);\n"
        "                      Navigator.of(context).maybePop();\n"
        "                    },\n"
        "                  ),\n"
        "              ],\n"
        "            ),\n"
        "          ),\n"
        "        ),\n"
        "      ),\n"
        "    );\n"
        "  }\n"
        "\n"
        "  // ---- build ------------------------------------------------------------\n",
        "                ),\n"
        "                if (widget.onUseAyah != null)\n"
        "                  _SheetAction(\n"
        "                    palette: _p,\n"
        "                    icon: Icons.movie_creation_outlined,\n"
        "                    label: _s.t('mushaf.useInStudio'),\n"
        "                    highlighted: true,\n"
        "                    onTap: () {\n"
        "                      Navigator.pop(sheetCtx);\n"
        "                      widget.onUseAyah!(ayah);\n"
        "                      Navigator.of(context).maybePop();\n"
        "                    },\n"
        "                  ),\n"
        "              ],\n"
        "            ),\n"
        "          ),\n"
        "        ),\n"
        "      ),\n"
        "    );\n"
        "  }\n"
        "\n"
        f"  // {MARKER_OPEN}: reciter list for one ayah's surah -- streaming and\n"
        "  // offline-download live in the sheet widget itself (below), so this\n"
        "  // screen's state doesn't grow a second set of download/playback fields.\n"
        "  void _openReciterSheet(Ayah ayah) {\n"
        "    showModalBottomSheet<void>(\n"
        "      context: context,\n"
        "      backgroundColor: _p.surface,\n"
        "      showDragHandle: true,\n"
        "      isScrollControlled: true,\n"
        "      shape: const RoundedRectangleBorder(\n"
        "        borderRadius: BorderRadius.vertical(top: Radius.circular(22)),\n"
        "      ),\n"
        "      builder: (_) => Directionality(\n"
        "        textDirection: TextDirection.rtl,\n"
        "        child: _ReciterListenSheet(\n"
        "          palette: _p,\n"
        "          surahNum: ayah.surahNum,\n"
        "          surahName: ayah.surah,\n"
        "        ),\n"
        "      ),\n"
        "    );\n"
        "  }\n"
        "\n"
        "  // ---- build ------------------------------------------------------------\n",
        "mushaf_screen.dart: _openReciterSheet on _MushafScreenState",
        skip_if=MARKER_OPEN,
    )

    # -----------------------------------------------------------------
    # 4) the sheet widget itself, appended after _SheetAction.
    # -----------------------------------------------------------------
    apply_literal(
        MUSHAF,
        "class _SheetAction extends StatelessWidget {\n"
        "  final MushafPalette palette;\n"
        "  final IconData icon;\n"
        "  final String label;\n"
        "  final VoidCallback onTap;\n"
        "  final bool highlighted;\n"
        "  const _SheetAction({\n"
        "    required this.palette,\n"
        "    required this.icon,\n"
        "    required this.label,\n"
        "    required this.onTap,\n"
        "    this.highlighted = false,\n"
        "  });\n"
        "\n"
        "  @override\n"
        "  Widget build(BuildContext context) {\n"
        "    final p = palette;\n"
        "    return Padding(\n"
        "      padding: const EdgeInsets.only(bottom: 8),\n"
        "      child: PressableScale(\n"
        "        onTap: onTap,\n"
        "        child: Container(\n"
        "          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 13),\n"
        "          decoration: BoxDecoration(\n"
        "            color: highlighted\n"
        "                ? p.gold.withValues(alpha: 0.14)\n"
        "                : p.surfaceRaised,\n"
        "            borderRadius: BorderRadius.circular(12),\n"
        "            border: Border.all(\n"
        "                color: highlighted\n"
        "                    ? p.gold.withValues(alpha: 0.6)\n"
        "                    : p.hairline),\n"
        "          ),\n"
        "          child: Row(\n"
        "            children: [\n"
        "              Icon(icon,\n"
        "                  size: 19, color: highlighted ? p.goldBright : p.gold),\n"
        "              const SizedBox(width: 12),\n"
        "              Text(label,\n"
        "                  style: GoogleFonts.tajawal(\n"
        "                      color: highlighted ? p.goldBright : p.text,\n"
        "                      fontSize: 13.5,\n"
        "                      fontWeight: FontWeight.w700)),\n"
        "            ],\n"
        "          ),\n"
        "        ),\n"
        "      ),\n"
        "    );\n"
        "  }\n"
        "}\n",
        "class _SheetAction extends StatelessWidget {\n"
        "  final MushafPalette palette;\n"
        "  final IconData icon;\n"
        "  final String label;\n"
        "  final VoidCallback onTap;\n"
        "  final bool highlighted;\n"
        "  const _SheetAction({\n"
        "    required this.palette,\n"
        "    required this.icon,\n"
        "    required this.label,\n"
        "    required this.onTap,\n"
        "    this.highlighted = false,\n"
        "  });\n"
        "\n"
        "  @override\n"
        "  Widget build(BuildContext context) {\n"
        "    final p = palette;\n"
        "    return Padding(\n"
        "      padding: const EdgeInsets.only(bottom: 8),\n"
        "      child: PressableScale(\n"
        "        onTap: onTap,\n"
        "        child: Container(\n"
        "          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 13),\n"
        "          decoration: BoxDecoration(\n"
        "            color: highlighted\n"
        "                ? p.gold.withValues(alpha: 0.14)\n"
        "                : p.surfaceRaised,\n"
        "            borderRadius: BorderRadius.circular(12),\n"
        "            border: Border.all(\n"
        "                color: highlighted\n"
        "                    ? p.gold.withValues(alpha: 0.6)\n"
        "                    : p.hairline),\n"
        "          ),\n"
        "          child: Row(\n"
        "            children: [\n"
        "              Icon(icon,\n"
        "                  size: 19, color: highlighted ? p.goldBright : p.gold),\n"
        "              const SizedBox(width: 12),\n"
        "              Text(label,\n"
        "                  style: GoogleFonts.tajawal(\n"
        "                      color: highlighted ? p.goldBright : p.text,\n"
        "                      fontSize: 13.5,\n"
        "                      fontWeight: FontWeight.w700)),\n"
        "            ],\n"
        "          ),\n"
        "        ),\n"
        "      ),\n"
        "    );\n"
        "  }\n"
        "}\n"
        "\n"
        f"// {MARKER_SHEET}: reciter list for a single surah, opened from the ayah\n"
        "// actions sheet. Self-contained -- owns its own search text, per-reciter\n"
        "// download progress, and the one active player -- so nothing needs\n"
        "// adding to _MushafScreenState, and the sheet's state simply goes away\n"
        "// when it's closed (its dispose() stops playback and frees the player).\n"
        "//\n"
        "// Downloads are tracked in a Map<int, double?> keyed by reciter index\n"
        "// rather than a single `int? downloading` -- unlike the studio's own\n"
        "// reciter panel (S104), that means starting reciter B's download does\n"
        "// not have to wait for reciter A's to finish; each entry in the map\n"
        "// updates independently as ReciterAudioService reports progress.\n"
        "// ReciterAudioService itself already caches to disk permanently, so a\n"
        "// completed download here IS the offline copy -- nothing extra to do\n"
        "// to make the surah available without a connection afterwards.\n"
        "class _ReciterListenSheet extends StatefulWidget {\n"
        "  final MushafPalette palette;\n"
        "  final int surahNum;\n"
        "  final String surahName;\n"
        "\n"
        "  const _ReciterListenSheet({\n"
        "    required this.palette,\n"
        "    required this.surahNum,\n"
        "    required this.surahName,\n"
        "  });\n"
        "\n"
        "  @override\n"
        "  State<_ReciterListenSheet> createState() => _ReciterListenSheetState();\n"
        "}\n"
        "\n"
        "class _ReciterListenSheetState extends State<_ReciterListenSheet> {\n"
        "  final _searchCtrl = TextEditingController();\n"
        "  String _query = '';\n"
        "\n"
        "  // One entry per reciter currently downloading; absent = idle. Several\n"
        "  // reciters can be present at once -- see the class comment above.\n"
        "  final Map<int, double?> _progress = {};\n"
        "  final Set<int> _cached = {};\n"
        "  int? _playingIndex;\n"
        "  VideoPlayerController? _player;\n"
        "\n"
        "  @override\n"
        "  void dispose() {\n"
        "    _searchCtrl.dispose();\n"
        "    _player?.dispose();\n"
        "    super.dispose();\n"
        "  }\n"
        "\n"
        "  Future<void> _stopPlayer() async {\n"
        "    final old = _player;\n"
        "    _player = null;\n"
        "    if (old != null) {\n"
        "      await old.pause();\n"
        "      await old.dispose();\n"
        "    }\n"
        "  }\n"
        "\n"
        "  Future<void> _togglePlay(int i) async {\n"
        "    if (_playingIndex == i) {\n"
        "      await _stopPlayer();\n"
        "      if (mounted) setState(() => _playingIndex = null);\n"
        "      return;\n"
        "    }\n"
        "    await _stopPlayer();\n"
        "    if (!mounted) return;\n"
        "    setState(() {\n"
        "      _playingIndex = i;\n"
        "      if (!_cached.contains(i)) _progress[i] = null;\n"
        "    });\n"
        "    try {\n"
        "      final path = await ReciterAudioService.downloadSurah(\n"
        "        displayName: kReciters[i],\n"
        "        surahNum: widget.surahNum,\n"
        "        onProgress: (p) {\n"
        "          if (mounted) setState(() => _progress[i] = p);\n"
        "        },\n"
        "      );\n"
        "      if (!mounted) return;\n"
        "      final c = VideoPlayerController.file(File(path));\n"
        "      await c.initialize();\n"
        "      if (!mounted) {\n"
        "        c.dispose();\n"
        "        return;\n"
        "      }\n"
        "      c.addListener(() {\n"
        "        if (!mounted || _player != c) return;\n"
        "        final v = c.value;\n"
        "        if (!v.isPlaying &&\n"
        "            v.duration > Duration.zero &&\n"
        "            v.position >= v.duration) {\n"
        "          setState(() => _playingIndex = null);\n"
        "        }\n"
        "      });\n"
        "      await c.play();\n"
        "      if (!mounted) {\n"
        "        c.dispose();\n"
        "        return;\n"
        "      }\n"
        "      setState(() {\n"
        "        _player = c;\n"
        "        _cached.add(i);\n"
        "        _progress.remove(i);\n"
        "      });\n"
        "    } on ReciterAudioException catch (e) {\n"
        "      if (!mounted) return;\n"
        "      setState(() {\n"
        "        _progress.remove(i);\n"
        "        if (_playingIndex == i) _playingIndex = null;\n"
        "      });\n"
        "      ScaffoldMessenger.of(context)\n"
        "          .showSnackBar(SnackBar(content: Text(e.message)));\n"
        "    } catch (_) {\n"
        "      if (!mounted) return;\n"
        "      setState(() {\n"
        "        _progress.remove(i);\n"
        "        if (_playingIndex == i) _playingIndex = null;\n"
        "      });\n"
        "    }\n"
        "  }\n"
        "\n"
        "  Future<void> _downloadOnly(int i) async {\n"
        "    if (_progress.containsKey(i) || _cached.contains(i)) return;\n"
        "    setState(() => _progress[i] = null);\n"
        "    try {\n"
        "      await ReciterAudioService.downloadSurah(\n"
        "        displayName: kReciters[i],\n"
        "        surahNum: widget.surahNum,\n"
        "        onProgress: (p) {\n"
        "          if (mounted) setState(() => _progress[i] = p);\n"
        "        },\n"
        "      );\n"
        "      if (!mounted) return;\n"
        "      setState(() {\n"
        "        _progress.remove(i);\n"
        "        _cached.add(i);\n"
        "      });\n"
        "    } on ReciterAudioException catch (e) {\n"
        "      if (!mounted) return;\n"
        "      setState(() => _progress.remove(i));\n"
        "      ScaffoldMessenger.of(context)\n"
        "          .showSnackBar(SnackBar(content: Text(e.message)));\n"
        "    } catch (_) {\n"
        "      if (!mounted) return;\n"
        "      setState(() => _progress.remove(i));\n"
        "    }\n"
        "  }\n"
        "\n"
        "  @override\n"
        "  Widget build(BuildContext context) {\n"
        "    final p = widget.palette;\n"
        "    final names = kReciters;\n"
        "    final q = _query.trim();\n"
        "    final shown = [\n"
        "      for (var i = 0; i < names.length; i++)\n"
        "        if (q.isEmpty || names[i].contains(q)) i,\n"
        "    ];\n"
        "    return SafeArea(\n"
        "      child: Padding(\n"
        "        padding: const EdgeInsets.fromLTRB(18, 4, 18, 12),\n"
        "        child: Column(\n"
        "          mainAxisSize: MainAxisSize.min,\n"
        "          crossAxisAlignment: CrossAxisAlignment.stretch,\n"
        "          children: [\n"
        "            Text('سورة ${widget.surahName} — استماع وتنزيل',\n"
        "                textAlign: TextAlign.center,\n"
        "                style: GoogleFonts.tajawal(\n"
        "                    color: p.text,\n"
        "                    fontSize: 14,\n"
        "                    fontWeight: FontWeight.w700)),\n"
        "            const SizedBox(height: 4),\n"
        "            Text('التشغيل والتنزيل لكامل السورة',\n"
        "                textAlign: TextAlign.center,\n"
        "                style:\n"
        "                    GoogleFonts.tajawal(color: p.textDim, fontSize: 11.5)),\n"
        "            const SizedBox(height: 10),\n"
        "            TextField(\n"
        "              controller: _searchCtrl,\n"
        "              onChanged: (v) => setState(() => _query = v),\n"
        "              style: GoogleFonts.tajawal(color: p.text, fontSize: 13),\n"
        "              decoration: InputDecoration(\n"
        "                hintText: 'ابحث عن قارئ',\n"
        "                hintStyle:\n"
        "                    GoogleFonts.tajawal(color: p.textDim, fontSize: 13),\n"
        "                prefixIcon: Icon(Icons.search, color: p.textDim, size: 19),\n"
        "                isDense: true,\n"
        "                filled: true,\n"
        "                fillColor: p.surfaceRaised,\n"
        "                border: OutlineInputBorder(\n"
        "                    borderRadius: BorderRadius.circular(10),\n"
        "                    borderSide: BorderSide(color: p.hairline)),\n"
        "              ),\n"
        "            ),\n"
        "            const SizedBox(height: 8),\n"
        "            SizedBox(\n"
        "              height: 340,\n"
        "              child: shown.isEmpty\n"
        "                  ? Center(\n"
        "                      child: Text('لا يوجد قارئ بهذا الاسم',\n"
        "                          style: GoogleFonts.tajawal(\n"
        "                              color: p.textDim, fontSize: 12.5)))\n"
        "                  : ListView.separated(\n"
        "                      itemCount: shown.length,\n"
        "                      separatorBuilder: (_, __) => const SizedBox(height: 6),\n"
        "                      itemBuilder: (c, idx) {\n"
        "                        final i = shown[idx];\n"
        "                        final downloading = _progress.containsKey(i);\n"
        "                        final progress = _progress[i];\n"
        "                        final playing = _playingIndex == i;\n"
        "                        return Container(\n"
        "                          padding: const EdgeInsets.symmetric(\n"
        "                              horizontal: 12, vertical: 6),\n"
        "                          decoration: BoxDecoration(\n"
        "                            color: playing\n"
        "                                ? p.gold.withValues(alpha: 0.12)\n"
        "                                : p.surfaceRaised,\n"
        "                            borderRadius: BorderRadius.circular(12),\n"
        "                            border: Border.all(\n"
        "                                color: playing\n"
        "                                    ? p.gold.withValues(alpha: 0.6)\n"
        "                                    : p.hairline),\n"
        "                          ),\n"
        "                          child: Row(\n"
        "                            children: [\n"
        "                              Expanded(\n"
        "                                child: Text(names[i],\n"
        "                                    style: GoogleFonts.tajawal(\n"
        "                                        color: p.text,\n"
        "                                        fontSize: 13.5,\n"
        "                                        fontWeight: FontWeight.w600)),\n"
        "                              ),\n"
        "                              if (downloading)\n"
        "                                SizedBox(\n"
        "                                  width: 34,\n"
        "                                  height: 34,\n"
        "                                  child: Padding(\n"
        "                                    padding: const EdgeInsets.all(8),\n"
        "                                    child: CircularProgressIndicator(\n"
        "                                        strokeWidth: 2.2,\n"
        "                                        value: progress,\n"
        "                                        color: p.goldBright),\n"
        "                                  ),\n"
        "                                )\n"
        "                              else ...[\n"
        "                                IconButton(\n"
        "                                  tooltip: 'تنزيل للقراءة بلا إنترنت',\n"
        "                                  icon: Icon(\n"
        "                                      _cached.contains(i)\n"
        "                                          ? Icons.check_circle\n"
        "                                          : Icons.download_outlined,\n"
        "                                      color: _cached.contains(i)\n"
        "                                          ? const Color(0xFF43A047)\n"
        "                                          : p.gold,\n"
        "                                      size: 20),\n"
        "                                  onPressed: _cached.contains(i)\n"
        "                                      ? null\n"
        "                                      : () => _downloadOnly(i),\n"
        "                                ),\n"
        "                                IconButton(\n"
        "                                  tooltip: playing ? 'إيقاف' : 'تشغيل',\n"
        "                                  icon: Icon(\n"
        "                                      playing\n"
        "                                          ? Icons.pause_circle_outline\n"
        "                                          : Icons.play_circle_outline,\n"
        "                                      color: p.goldBright,\n"
        "                                      size: 24),\n"
        "                                  onPressed: () => _togglePlay(i),\n"
        "                                ),\n"
        "                              ],\n"
        "                            ],\n"
        "                          ),\n"
        "                        );\n"
        "                      },\n"
        "                    ),\n"
        "            ),\n"
        "          ],\n"
        "        ),\n"
        "      ),\n"
        "    );\n"
        "  }\n"
        "}\n",
        "mushaf_screen.dart: append _ReciterListenSheet widget",
        skip_if=MARKER_SHEET,
    )

    print("\n=== S138 gauntlet loop ledger ===")
    for label, status in LEDGER:
        print(f"[{status}] {label}")
    print("==================================\n")
    print("Reminder: this reuses lib/services/reciter_audio_service.dart and")
    print("kReciters from lib/data/studio_presets.dart (both added in S104) --")
    print("no new dependency; video_player and http are already in pubspec.yaml.")


if __name__ == "__main__":
    main()
